# Generated by Django 6.0.2 on 2026-02-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('MORNING', 'Morning (7am - 3pm)'), ('EVENING', 'Evening (3pm - 11pm)'), ('NIGHT', 'Night (11pm - 7am)')], max_length=10)),
                ('location', models.CharField(default='P5 Control Room', max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.member')),
            ],
        ),
    ]
