# Generated by Django 6.0.2 on 2026-02-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_mo_qualified',
            field=models.BooleanField(default=False, help_text='Counted for Maintenance & Operations statistics'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='group',
            field=models.CharField(choices=[('ATLAS', 'ATLAS'), ('CMS', 'CMS'), ('ALICE', 'ALICE'), ('LHCb', 'LHCb'), ('TOTEM', 'TOTEM'), ('LHCf', 'LHCf'), ('MOEDAL', 'MoEDAL'), ('FASER', 'FASER'), ('SND', 'SND@LHC')], max_length=10),
        ),
    ]
