# Generated by Django 6.0.2 on 2026-02-07 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_member_is_mo_qualified_alter_analysis_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='ref_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='cern_status',
            field=models.CharField(choices=[('USER', 'User'), ('STAFF', 'Staff'), ('FELLOW', 'Fellow'), ('DOCTORAL STUDENT', 'Doctoral Student')], default='USER', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institute'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shift',
            name='type',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=10),
        ),
    ]
