# Generated by Django 6.0.2 on 2026-02-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cern_status',
            field=models.CharField(choices=[('USER', 'User (Physicist)'), ('STAFF', 'CERN Staff'), ('FELLOW', 'Research Fellow')], default='USER', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
