# Generated by Django 6.0.2 on 2026-02-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('ref_code', models.CharField(help_text='e.g., HIGG-2022-14', max_length=20, unique=True)),
                ('group', models.CharField(choices=[('HIGG', 'Higgs'), ('EXOT', 'Exotics'), ('SUSY', 'Supersymmetry'), ('STDM', 'Standard Model'), ('TOP', 'Top Physics'), ('ION', 'Heavy Ions')], max_length=10)),
                ('phase', models.IntegerField(choices=[(0, 'Phase 0 (Idea)'), (1, 'Phase 1 (Analysis)'), (2, 'Phase 2 (Review)'), (3, 'Published')], default=0)),
                ('status_text', models.CharField(default='Draft', max_length=100)),
                ('target_journal', models.CharField(blank=True, max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='papers', to='api.member')),
            ],
        ),
    ]
