# Generated by Django 6.0.2 on 2026-03-01 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LhcSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signal_type', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('status', models.CharField(choices=[('OK', 'Healthy'), ('WARNING', 'Degraded'), ('FAULT', 'CRITICAL (Quench)')], default='OK', max_length=10)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='telemetry.lhcsector')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
